---
containers_volumes: /tmp
certificates_directory: /tmp/certs

haproxy_user: haproxy
haproxy_group: haproxy
haproxy_image_tag: latest

prometheus_user: prometheus
prometheus_group: prometheus
prometheus_image_tag: latest

grafana_user: grafana
grafana_group: grafana
grafana_image_tag: latest
