---
- name: Create containers volume's directory
  ansible.builtin.file:
    path: "{{ containers_volumes }}"
    state: directory
    mode: '0755'

- name: Create docker network
  community.docker.docker_network:
    name: sou_network

- name: Setup Prometheus
  ansible.builtin.include_tasks:
    file: setup_prometheus.yml

- name: Setup Grafana
  ansible.builtin.include_tasks: 
    file: setup_grafana.yml

- name: HTTPS
  ansible.builtin.include_tasks: 
    file: https.yml

- name: Setup HAProxy
  ansible.builtin.include_tasks: 
    file: setup_haproxy.yml