---
- name: Add HAProxy group
  ansible.builtin.group:
    name: "{{ haproxy_group }}"
    state: present

- name: Add HAProxy user
  ansible.builtin.user:
    name: "{{ haproxy_user }}"
    groups: "{{ haproxy_group }}"

- name: Create HAProxy config dir
  ansible.builtin.file:
    path: "{{ containers_volumes }}/haproxy/config"
    state: directory
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    mode: '0755'

- name: Copy HAProxy config file
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "{{ containers_volumes }}/haproxy/config/haproxy.cfg"
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    mode: '0644'

- name: Create HAProxy certs dir
  ansible.builtin.file:
    path: "{{ containers_volumes }}/haproxy/certs"
    state: directory
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    mode: '0755'

- name: Copy PEM file to HAProxy certs dir
  ansible.builtin.copy:
    src: "{{ certificates_directory }}/localhost-comb.pem"
    dest: "{{ containers_volumes }}/haproxy/certs"
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    mode: '0644'
    remote_src: true

- name: Create HAProxy container
  community.docker.docker_container:
    name: haproxy
    hostname: haproxy
    networks:
      - name: sou_network
    image: "haproxytech/haproxy-alpine:{{ haproxy_image_tag }}"
    volumes:
      - "{{ containers_volumes }}/haproxy/config/:/etc/haproxy/"
      - "{{ containers_volumes }}/haproxy/certs/:/haproxy/certs/:ro"
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "443:443"
