---
- name: Add Grafana group
  ansible.builtin.group:
    name: "{{ grafana_group }}"
    state: present

- name: Add Grafana user
  ansible.builtin.user:
    name: "{{ grafana_user }}"
    groups: "{{ grafana_group }}"

- name: Create Grafana config dir
  ansible.builtin.file:
    path: "{{ containers_volumes }}/grafana/config"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0755'

- name: Create Grafana data dir
  ansible.builtin.file:
    path: "{{ containers_volumes }}/grafana/data"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0755'

- name: Copy Grafana config file
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: "{{ containers_volumes }}/grafana/config/grafana.ini"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0644'

- name: Create Grafana container
  community.docker.docker_container:
    name: grafana
    hostname: grafana
    networks:
      - name: sou_network
    image: "grafana/grafana:{{ grafana_image_tag }}"
    volumes:
      - "{{ containers_volumes }}/grafana/config/:/etc/grafana/"
      - "{{ containers_volumes }}/grafana/data/:/data/grafana/"
    expose:
      - 3000
    ports:
      - "3000:3000"
